# Generated by Django 4.2.1 on 2023-07-20 06:53

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=certificates.models.certificate_file_path,
            ),
        ),
    ]
